[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build:functions && npm run build"

[build.environment]
  NODE_VERSION = "22.14.10"
  NPM_FLAGS = "--legacy-peer-deps"

[dev]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
